### ISSUE TITLE
Supporting Multiple Domains in a Single Multi-tenant App

### ISSUE THREAD

**Issue by brianmba** [KMarshland/heroku-ssl#2]
This looks like a tremendously valuable gem and I'm curious if you have any thoughts on how we might adapt it for use on our small niche CMS app.

We power many different client domains with our software and some are interested in accessing their site over https however Heroku doesn't allow unlimited certs so I'm curious if you have any thoughts on how we could implement ssl when each client would need to have their own domain/dns settings etc in our multi-tenant app.

Thanks.

**Comment by KMarshland** [comment]
Interesting problem. Before I answer, I'd like to verify my understanding of your system:
1. You have a single Heroku app (that you have full control over).
2. Users can build their site through this app
3. They can then configure their domains to point at your-app.herokudns.com
4. When your app gets a request, it detects which domain the request came from, and serves the appropriate site. 

Is that a valid assessment?

**Comment by brianmba** [comment]
That's correct, it's largely based on the subdomains in Rails approach I believe originated at Basecamp - we just allow clients to then add custom domains to replace the branded subdomain.

I don't understand enough of the inner workings of ssl certs to appreciate how/if multiple disparate parties can use the same cert and if they can do it without a security issue.

**Comment by KMarshland** [comment]
Since the certificate validation happens on Heroku's side, we could simply use one certificate for all of your domain names, and upload that certificate to Heroku. You could do that using this gem simply by keeping track of all your domains, and passing that in when it asks for the domains to register; I suspect you already run something like `heroku domains:add` every time a new domain is added.

However, Let's Encrypt limits us to at most 100 names per certificate: https://letsencrypt.org/docs/rate-limits/. I imagine you have more than 100 users, so you can't just use one certificate for all of these. At this point you would have to generate a certificate for every single one of your client's domains, then configure heroku to use all of these certificates. You can certainly use this gem to generate the certificates, but you'd have to configure the heroku side of things yourself (see http://stackoverflow.com/questions/13448012/multiple-ssl-certificates-in-one-heroku-application).

**Comment by KMarshland** [comment]
I should note that to generate a certificate for a given domain, you can parse the output of running `heroku run rake heroku_ssl:generate_certs #{email} #{domain} --app #{app"`

**Comment by brianmba** [comment]
Ah, terrific. I appreciate the input, this will help us map out our plan of action.
